// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_zTghVyF3Avm_77GiVX3AQZOLNhw8u8',
    appId: '1:610554485871:web:2ff5e8e28a491fb06cc19a',
    messagingSenderId: '610554485871',
    projectId: 'flutter-chat-app-f91ce',
    authDomain: 'flutter-chat-app-f91ce.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f91ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBEpYk8nkTQo0B1dzMpzmXNOQX4Oao0jU',
    appId: '1:610554485871:android:9808ffd5117618ea6cc19a',
    messagingSenderId: '610554485871',
    projectId: 'flutter-chat-app-f91ce',
    storageBucket: 'flutter-chat-app-f91ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNgQm6fLpsZvcRMS3Xjnorct_e4wMp3w',
    appId: '1:610554485871:ios:459dd08a2c5876056cc19a',
    messagingSenderId: '610554485871',
    projectId: 'flutter-chat-app-f91ce',
    storageBucket: 'flutter-chat-app-f91ce.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZNgQm6fLpsZvcRMS3Xjnorct_e4wMp3w',
    appId: '1:610554485871:ios:f19108d780f7b42f6cc19a',
    messagingSenderId: '610554485871',
    projectId: 'flutter-chat-app-f91ce',
    storageBucket: 'flutter-chat-app-f91ce.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
